services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  DataFixtures\:
    resource: '%kernel.project_dir%/database/DataFixtures/*'

  _instanceof:
    Doctrine\Bundle\FixturesBundle\Fixture:
      tags:
        - { name: 'doctrine.fixture.orm', priority: 20 }